# Generated by Django 4.2.6 on 2023-10-09 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('resepien', models.ForeignKey(default='Пользователь не найден', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='received_mess', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default='Пользователь не найден', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sent_mess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
