# Generated by Django 4.2.6 on 2023-10-30 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chat', models.CharField(choices=[('C', 'Чат'), ('D', 'Диалог')], default='D', max_length=1)),
                ('members', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_readed', models.BooleanField(choices=[(False, 'Не прочитано'), (True, 'Прочитано')], default=0, verbose_name='Статус')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(default='Пользователь не найден', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sent_mess', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-time_create'],
            },
        ),
        migrations.DeleteModel(
            name='Messange',
        ),
    ]
