# Generated by Django 5.0.7 on 2024-08-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title_chat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название группового чата'),
        ),
    ]
