# Generated by Django 5.0.7 on 2024-08-31 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_title_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_chat_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='group_chat_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/chats/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
