# Generated by Django 5.0.7 on 2024-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(to='users.userinfo', verbose_name='Друзья'),
        ),
    ]
