# Generated by Django 5.0.7 on 2024-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
